version: '3'

services:
  # MySQL
  db:
    image: mysql:8.0
    container_name: webapp-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - webapp-db-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  webapp-db-data:
