// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Carts  string
	Orders string
	Phones string
	Users  string
	Webapp string
}{
	Carts:  "carts",
	Orders: "orders",
	Phones: "phones",
	Users:  "users",
	Webapp: "webapp",
}
