// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Users", testUsers)
	t.Run("Webapps", testWebapps)
}

func TestDelete(t *testing.T) {
	t.Run("Users", testUsersDelete)
	t.Run("Webapps", testWebappsDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Users", testUsersQueryDeleteAll)
	t.Run("Webapps", testWebappsQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Users", testUsersSliceDeleteAll)
	t.Run("Webapps", testWebappsSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Users", testUsersExists)
	t.Run("Webapps", testWebappsExists)
}

func TestFind(t *testing.T) {
	t.Run("Users", testUsersFind)
	t.Run("Webapps", testWebappsFind)
}

func TestBind(t *testing.T) {
	t.Run("Users", testUsersBind)
	t.Run("Webapps", testWebappsBind)
}

func TestOne(t *testing.T) {
	t.Run("Users", testUsersOne)
	t.Run("Webapps", testWebappsOne)
}

func TestAll(t *testing.T) {
	t.Run("Users", testUsersAll)
	t.Run("Webapps", testWebappsAll)
}

func TestCount(t *testing.T) {
	t.Run("Users", testUsersCount)
	t.Run("Webapps", testWebappsCount)
}

func TestHooks(t *testing.T) {
	t.Run("Users", testUsersHooks)
	t.Run("Webapps", testWebappsHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
	t.Run("Webapps", testWebappsInsert)
	t.Run("Webapps", testWebappsInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Users", testUsersReload)
	t.Run("Webapps", testWebappsReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Users", testUsersReloadAll)
	t.Run("Webapps", testWebappsReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Users", testUsersSelect)
	t.Run("Webapps", testWebappsSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Users", testUsersUpdate)
	t.Run("Webapps", testWebappsUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Users", testUsersSliceUpdateAll)
	t.Run("Webapps", testWebappsSliceUpdateAll)
}
